import React from 'react';
import { Space, Tag, Typography } from '@arco-design/web-react';
import { SearchColumn } from '@/components/UniversalSearch';

const { Text } = Typography;

// 弹药数据
export const ammunitionData = [
  {
    id: 1,
    name: '红箭-12反坦克导弹',
    abbreviation: 'HJ-12',
    caliber: 120,
    type: '反坦克导弹',
    weight: 22,
    length: 1200,
    minRange: 0.3,
    maxRange: 8,
    accuracy: 5,
    power: '高',
    guidance: '激光制导',
    manufacturer: '中国兵器工业集团',
    country: '中国',
    compatibleArtillery: [
      {
        id: 1,
        name: 'PLZ-05自行榴弹炮',
        caliber: 155,
        type: '自行榴弹炮',
        country: '中国',
      },
    ],
  },
  {
    id: 2,
    name: 'AGM-114地狱火导弹',
    abbreviation: 'Hellfire',
    caliber: 178,
    type: '空对地导弹',
    weight: 45,
    length: 1625,
    minRange: 0.5,
    maxRange: 11,
    accuracy: 3,
    power: '高',
    guidance: '激光制导',
    manufacturer: '洛克希德·马丁',
    country: '美国',
  },
  {
    id: 3,
    name: 'AIM-120先进中程空对空导弹',
    abbreviation: 'AMRAAM',
    caliber: 178,
    type: '空对空导弹',
    weight: 161,
    length: 3650,
    minRange: 1,
    maxRange: 180,
    accuracy: 10,
    power: '中',
    guidance: '雷达制导',
    manufacturer: '雷神公司',
    country: '美国',
  },
  {
    id: 4,
    name: '飞鱼反舰导弹',
    abbreviation: 'Exocet',
    caliber: 350,
    type: '反舰导弹',
    weight: 670,
    length: 4700,
    minRange: 5,
    maxRange: 180,
    accuracy: 15,
    power: '极高',
    guidance: '惯性+雷达制导',
    manufacturer: 'MBDA',
    country: '法国',
  },
  {
    id: 5,
    name: 'RPG-7火箭推进榴弹',
    abbreviation: 'RPG-7',
    caliber: 85,
    type: '火箭弹',
    weight: 6.3,
    length: 950,
    minRange: 0.05,
    maxRange: 0.5,
    accuracy: 50,
    power: '中',
    guidance: '无制导',
    manufacturer: '俄罗斯战术导弹公司',
    country: '俄罗斯',
  },
  {
    id: 6,
    name: '标枪反坦克导弹',
    abbreviation: 'Javelin',
    caliber: 127,
    type: '反坦克导弹',
    weight: 22.8,
    length: 1080,
    minRange: 0.15,
    maxRange: 4.75,
    accuracy: 5,
    power: '高',
    guidance: '红外成像制导',
    manufacturer: '雷神公司',
    country: '美国',
  },
  // 新增中国弹药产品
  {
    id: 7,
    name: '红箭-8反坦克导弹',
    abbreviation: 'HJ-8',
    caliber: 120,
    type: '反坦克导弹',
    weight: 24.5,
    length: 875,
    minRange: 0.1,
    maxRange: 3,
    accuracy: 8,
    power: '高',
    guidance: '有线制导',
    manufacturer: '中国兵器工业集团',
    country: '中国',
  },
  {
    id: 8,
    name: '霹雳-15空对空导弹',
    abbreviation: 'PL-15',
    caliber: 200,
    type: '空对空导弹',
    weight: 180,
    length: 4000,
    minRange: 0.5,
    maxRange: 200,
    accuracy: 8,
    power: '高',
    guidance: '主动雷达制导',
    manufacturer: '中国航天科工集团',
    country: '中国',
  },
  {
    id: 9,
    name: '鹰击-18反舰导弹',
    abbreviation: 'YJ-18',
    caliber: 533,
    type: '反舰导弹',
    weight: 1800,
    length: 8000,
    minRange: 10,
    maxRange: 540,
    accuracy: 12,
    power: '极高',
    guidance: '惯性+雷达制导',
    manufacturer: '中国航天科工集团',
    country: '中国',
  },
  {
    id: 10,
    name: '155mm榴弹',
    abbreviation: '155HE',
    caliber: 155,
    type: '榴弹',
    weight: 43.5,
    length: 800,
    minRange: 3,
    maxRange: 30,
    accuracy: 25,
    power: '中',
    guidance: '无制导',
    manufacturer: '中国北方工业公司',
    country: '中国',
    compatibleArtillery: [
      {
        id: 1,
        name: 'PLZ-05自行榴弹炮',
        caliber: 155,
        type: '自行榴弹炮',
        country: '中国',
      },
      {
        id: 2,
        name: 'M777超轻型榴弹炮',
        caliber: 155,
        type: '牵引榴弹炮',
        country: '美国',
      },
      {
        id: 3,
        name: 'PzH 2000自行榴弹炮',
        caliber: 155,
        type: '自行榴弹炮',
        country: '德国',
      },
    ],
  },
  // 新增美国弹药产品
  {
    id: 11,
    name: '战斧巡航导弹',
    abbreviation: 'Tomahawk',
    caliber: 533,
    type: '巡航导弹',
    weight: 1200,
    length: 6200,
    minRange: 50,
    maxRange: 2500,
    accuracy: 10,
    power: '高',
    guidance: 'GPS+地形匹配',
    manufacturer: '雷神公司',
    country: '美国',
  },
  {
    id: 12,
    name: '爱国者防空导弹',
    abbreviation: 'Patriot',
    caliber: 254,
    type: '防空导弹',
    weight: 900,
    length: 5300,
    minRange: 3,
    maxRange: 160,
    accuracy: 15,
    power: '中',
    guidance: '雷达制导',
    manufacturer: '雷神公司',
    country: '美国',
  },
  {
    id: 13,
    name: '227mm火箭弹',
    abbreviation: 'M26',
    caliber: 227,
    type: '火箭弹',
    weight: 300,
    length: 4000,
    minRange: 10,
    maxRange: 70,
    accuracy: 30,
    power: '中',
    guidance: '无制导',
    manufacturer: '洛克希德·马丁',
    country: '美国',
  },
  // 新增俄罗斯弹药产品
  {
    id: 14,
    name: '伊斯坎德尔导弹',
    abbreviation: 'Iskander',
    caliber: 920,
    type: '弹道导弹',
    weight: 3800,
    length: 7600,
    minRange: 50,
    maxRange: 500,
    accuracy: 20,
    power: '极高',
    guidance: '惯性+GPS',
    manufacturer: '俄罗斯战术导弹公司',
    country: '俄罗斯',
  },
  {
    id: 15,
    name: 'S-300防空导弹',
    abbreviation: 'S-300',
    caliber: 300,
    type: '防空导弹',
    weight: 1500,
    length: 7500,
    minRange: 5,
    maxRange: 200,
    accuracy: 18,
    power: '高',
    guidance: '雷达制导',
    manufacturer: '俄罗斯战术导弹公司',
    country: '俄罗斯',
  },
  {
    id: 16,
    name: '122mm火箭弹',
    abbreviation: 'BM-21',
    caliber: 122,
    type: '火箭弹',
    weight: 66,
    length: 3000,
    minRange: 5,
    maxRange: 20,
    accuracy: 35,
    power: '中',
    guidance: '无制导',
    manufacturer: '乌拉尔机车厂',
    country: '俄罗斯',
  },
  // 新增德国弹药产品
  {
    id: 17,
    name: 'IRIS-T空对空导弹',
    abbreviation: 'IRIS-T',
    caliber: 127,
    type: '空对空导弹',
    weight: 87.4,
    length: 2940,
    minRange: 0.5,
    maxRange: 25,
    accuracy: 6,
    power: '中',
    guidance: '红外成像制导',
    manufacturer: '迪尔防务',
    country: '德国',
  },
  {
    id: 18,
    name: '227mm火箭弹',
    abbreviation: 'MARS',
    caliber: 227,
    type: '火箭弹',
    weight: 300,
    length: 4000,
    minRange: 10,
    maxRange: 70,
    accuracy: 30,
    power: '中',
    guidance: '无制导',
    manufacturer: '迪尔防务',
    country: '德国',
  },
  // 新增法国弹药产品
  {
    id: 19,
    name: '米卡空对空导弹',
    abbreviation: 'MICA',
    caliber: 160,
    type: '空对空导弹',
    weight: 112,
    length: 3100,
    minRange: 0.5,
    maxRange: 80,
    accuracy: 8,
    power: '中',
    guidance: '雷达/红外制导',
    manufacturer: 'MBDA',
    country: '法国',
  },
  {
    id: 20,
    name: '阿帕奇巡航导弹',
    abbreviation: 'Apache',
    caliber: 400,
    type: '巡航导弹',
    weight: 1230,
    length: 5200,
    minRange: 50,
    maxRange: 140,
    accuracy: 12,
    power: '高',
    guidance: '惯性+GPS',
    manufacturer: 'MBDA',
    country: '法国',
  },
  // 新增英国弹药产品
  {
    id: 21,
    name: '流星空对空导弹',
    abbreviation: 'Meteor',
    caliber: 178,
    type: '空对空导弹',
    weight: 185,
    length: 3650,
    minRange: 1,
    maxRange: 200,
    accuracy: 10,
    power: '高',
    guidance: '主动雷达制导',
    manufacturer: 'MBDA',
    country: '英国',
  },
  {
    id: 22,
    name: '风暴阴影巡航导弹',
    abbreviation: 'Storm Shadow',
    caliber: 450,
    type: '巡航导弹',
    weight: 1300,
    length: 5100,
    minRange: 50,
    maxRange: 560,
    accuracy: 15,
    power: '高',
    guidance: '惯性+GPS+地形匹配',
    manufacturer: 'MBDA',
    country: '英国',
  },
  // 新增以色列弹药产品
  {
    id: 23,
    name: '德比空对空导弹',
    abbreviation: 'Derby',
    caliber: 160,
    type: '空对空导弹',
    weight: 118,
    length: 3620,
    minRange: 0.5,
    maxRange: 63,
    accuracy: 8,
    power: '中',
    guidance: '主动雷达制导',
    manufacturer: '拉斐尔',
    country: '以色列',
  },
  {
    id: 24,
    name: '长钉反坦克导弹',
    abbreviation: 'Spike',
    caliber: 130,
    type: '反坦克导弹',
    weight: 26,
    length: 1200,
    minRange: 0.2,
    maxRange: 4,
    accuracy: 6,
    power: '高',
    guidance: '光纤制导',
    manufacturer: '拉斐尔',
    country: '以色列',
  },
  // 新增韩国弹药产品
  {
    id: 25,
    name: '天弓防空导弹',
    abbreviation: 'Cheongung',
    caliber: 200,
    type: '防空导弹',
    weight: 400,
    length: 4800,
    minRange: 3,
    maxRange: 40,
    accuracy: 20,
    power: '中',
    guidance: '雷达制导',
    manufacturer: '韩华系统',
    country: '韩国',
  },
  {
    id: 26,
    name: '海星反舰导弹',
    abbreviation: 'Haeseong',
    caliber: 350,
    type: '反舰导弹',
    weight: 650,
    length: 4500,
    minRange: 8,
    maxRange: 150,
    accuracy: 18,
    power: '高',
    guidance: '惯性+雷达制导',
    manufacturer: '韩华系统',
    country: '韩国',
  },
  {
    id: 27,
    name: 'CS/BME1型120毫米卫星制导迫弹',
    abbreviation: 'CS/BME1',
    caliber: 120,
    type: '迫击炮弹',
    weight: 15.8,
    length: 600,
    minRange: 0.5,
    maxRange: 7.2,
    accuracy: 10,
    power: '中',
    guidance: '卫星制导',
    manufacturer: '中国北方工业公司',
    country: '中国',
    compatibleArtillery: [
      {
        id: 8,
        name: '阿联酋AGRAB型120毫米自行迫击炮',
        caliber: 120,
        type: '自行迫击炮',
        country: '阿联酋',
      },
      {
        id: 9,
        name: '阿联酋Ghannatha级快速巡逻艇（NEMO迫炮塔）',
        caliber: 120,
        type: '舰载迫击炮',
        country: '阿联酋',
      },
      {
        id: 10,
        name: '法国Patria AMV模块化装甲车（NEMO迫炮塔）',
        caliber: 120,
        type: '车载迫击炮',
        country: '阿联酋',
      },
    ],
  },
  {
    id: 28,
    name: 'CS/BME3型81毫米卫星制导迫弹',
    abbreviation: 'CS/BME3',
    caliber: 81,
    type: '迫击炮弹',
    weight: 4.2,
    length: 400,
    minRange: 0.3,
    maxRange: 5.5,
    accuracy: 8,
    power: '中',
    guidance: '卫星制导',
    manufacturer: '中国北方工业公司',
    country: '中国',
    compatibleArtillery: [
      {
        id: 11,
        name: '塞尔维亚M69B型81毫米迫击炮',
        caliber: 81,
        type: '迫击炮',
        country: '阿联酋',
      },
    ],
  },
  {
    id: 29,
    name: 'CS/BME4型82毫米卫星制导迫弹',
    abbreviation: 'CS/BME4',
    caliber: 82,
    type: '迫击炮弹',
    weight: 4.5,
    length: 420,
    minRange: 0.3,
    maxRange: 5.8,
    accuracy: 8,
    power: '中',
    guidance: '卫星制导',
    manufacturer: '中国北方工业公司',
    country: '中国',
    compatibleArtillery: [
      {
        id: 12,
        name: '塞尔维亚M69A型82毫米迫击炮',
        caliber: 82,
        type: '迫击炮',
        country: '阿联酋',
      },
    ],
  },
  {
    id: 30,
    name: 'GP1型155毫米激光末制导炮弹',
    abbreviation: 'GP1',
    caliber: 155,
    type: '榴弹',
    weight: 43.5,
    length: 800,
    minRange: 3,
    maxRange: 30,
    accuracy: 5,
    power: '高',
    guidance: '激光末制导',
    manufacturer: '中国北方工业公司',
    country: '中国',
    compatibleArtillery: [
      {
        id: 15,
        name: '美国M109式155毫米加榴炮',
        caliber: 155,
        type: '自行榴弹炮',
        country: '阿联酋',
      },
      {
        id: 16,
        name: '南非G6式155毫米车载加榴炮',
        caliber: 155,
        type: '车载榴弹炮',
        country: '阿联酋',
      },
      {
        id: 17,
        name: '国产AH4型155毫米轻型榴弹炮',
        caliber: 155,
        type: '轻型榴弹炮',
        country: '阿联酋',
      },
      {
        id: 36,
        name: '国产SH15型155毫米车载加榴炮',
        caliber: 155,
        type: '车载榴弹炮',
        country: '阿联酋',
      },
    ],
  },
  {
    id: 31,
    name: 'GP11型155毫米卫星制导炮弹',
    abbreviation: 'GP11',
    caliber: 155,
    type: '榴弹',
    weight: 43.5,
    length: 800,
    minRange: 3,
    maxRange: 30,
    accuracy: 3,
    power: '高',
    guidance: '卫星制导',
    manufacturer: '中国北方工业公司',
    country: '中国',
    compatibleArtillery: [
      {
        id: 15,
        name: '美国M109式155毫米加榴炮',
        caliber: 155,
        type: '自行榴弹炮',
        country: '阿联酋',
      },
      {
        id: 16,
        name: '南非G6式155毫米车载加榴炮',
        caliber: 155,
        type: '车载榴弹炮',
        country: '阿联酋',
      },
      {
        id: 17,
        name: '国产AH4型155毫米轻型榴弹炮',
        caliber: 155,
        type: '轻型榴弹炮',
        country: '阿联酋',
      },
      {
        id: 36,
        name: '国产SH15型155毫米车载加榴炮',
        caliber: 155,
        type: '车载榴弹炮',
        country: '阿联酋',
      },
    ],
  },
];

// 弹药检索列配置
export const ammunitionColumns: SearchColumn[] = [
  {
    title: '弹药名称',
    dataIndex: 'name',
    width: 200,
    render: (value, record: any) => (
      <Space direction="vertical" size="mini">
        <Text bold>{value}</Text>
        <Text type="secondary" style={{ fontSize: '12px' }}>
          {record.abbreviation}
        </Text>
      </Space>
    ),
  },
  {
    title: '口径',
    dataIndex: 'caliber',
    width: 80,
    render: value => `${value}mm`,
    sorter: (a: any, b: any) => a.caliber - b.caliber,
  },
  {
    title: '类型',
    dataIndex: 'type',
    width: 120,
    render: value => <Tag color="blue">{value}</Tag>,
  },
  {
    title: '重量',
    dataIndex: 'weight',
    width: 80,
    render: value => `${value}kg`,
    sorter: (a: any, b: any) => a.weight - b.weight,
  },
  {
    title: '射程',
    dataIndex: 'maxRange',
    width: 100,
    render: (value, record: any) => `${record.minRange}-${value}km`,
    sorter: (a: any, b: any) => a.maxRange - b.maxRange,
  },
  {
    title: '制导方式',
    dataIndex: 'guidance',
    width: 140,
  },
  {
    title: '厂商',
    dataIndex: 'manufacturer',
    width: 180,
    ellipsis: true,
  },
  {
    title: '国家',
    dataIndex: 'country',
    width: 80,
    render: value => <Tag color="orange">{value}</Tag>,
  },
];

// 搜索字段配置
export const ammunitionSearchFields = [
  'name',
  'abbreviation',
  'type',
  'guidance',
  'manufacturer',
  'country',
];

// 搜索建议
export const ammunitionSuggestions = [
  '反坦克导弹',
  '空对空导弹',
  '巡航导弹',
  '火箭弹',
  '迫击炮弹',
  '榴弹',
  '激光制导',
  '雷达制导',
  '红外制导',
  '卫星制导',
  '中国',
  '美国',
  '俄罗斯',
  '法国',
  '阿联酋',
  '洛克希德·马丁',
  '雷神公司',
  'MBDA',
  '中国北方工业公司',
];
