import { SearchColumn } from '@/components/UniversalSearch';
import { Tag, Typography } from '@arco-design/web-react';

const { Text } = Typography;

// 火炮数据
export const artilleryData = [
  {
    id: 1,
    name: 'PLZ-05自行榴弹炮',
    caliber: 155,
    type: '自行榴弹炮',
    mobility: '履带式',
    muzzleVelocity: 930,
    range: 50,
    barrelLength: 8.1,
    elevationRange: '-5°~+70°',
    traverseRange: '360°',
    manufacturer: '中国北方工业公司',
    country: '中国',
    compatibleAmmunition: [
      {
        id: 10,
        name: '155mm榴弹',
        caliber: 155,
        type: '榴弹',
        guidance: '无制导',
      },
    ],
  },
  {
    id: 2,
    name: 'M777超轻型榴弹炮',
    caliber: 155,
    type: '牵引榴弹炮',
    mobility: '牵引式',
    muzzleVelocity: 827,
    range: 40,
    barrelLength: 6.4,
    elevationRange: '-5°~+70°',
    traverseRange: '±25°',
    manufacturer: 'BAE系统',
    country: '美国',
    compatibleAmmunition: [
      {
        id: 10,
        name: '155mm榴弹',
        caliber: 155,
        type: '榴弹',
        guidance: '无制导',
      },
      {
        id: 9,
        name: '鹰击-18反舰导弹',
        abbreviation: 'YJ-18',
        caliber: 533,
        type: '反舰导弹',
        weight: 1800,
        length: 8000,
        minRange: 10,
        maxRange: 540,
        accuracy: 12,
        power: '极高',
        guidance: '惯性+雷达制导',
        manufacturer: '中国航天科工集团',
        country: '中国',
      },
    ],
  },
  {
    id: 3,
    name: 'PzH 2000自行榴弹炮',
    caliber: 155,
    type: '自行榴弹炮',
    mobility: '履带式',
    muzzleVelocity: 940,
    range: 56,
    barrelLength: 8.1,
    elevationRange: '-2.5°~+65°',
    traverseRange: '360°',
    manufacturer: '克劳斯-玛菲',
    country: '德国',
  },
  {
    id: 4,
    name: 'CAESAR自行榴弹炮',
    caliber: 155,
    type: '自行榴弹炮',
    mobility: '轮式',
    muzzleVelocity: 810,
    range: 42,
    barrelLength: 6.5,
    elevationRange: '-5°~+66°',
    traverseRange: '±30°',
    manufacturer: '奈克斯特',
    country: '法国',
  },
  {
    id: 5,
    name: 'K9雷鸣自行榴弹炮',
    caliber: 155,
    type: '自行榴弹炮',
    mobility: '履带式',
    muzzleVelocity: 915,
    range: 40,
    barrelLength: 8.1,
    elevationRange: '-3°~+65°',
    traverseRange: '360°',
    manufacturer: '韩华系统',
    country: '韩国',
  },
  {
    id: 6,
    name: '2S19姆斯塔河自行榴弹炮',
    caliber: 152,
    type: '自行榴弹炮',
    mobility: '履带式',
    muzzleVelocity: 810,
    range: 25,
    barrelLength: 6.1,
    elevationRange: '-4°~+68°',
    traverseRange: '360°',
    manufacturer: '乌拉尔机车厂',
    country: '俄罗斯',
  },
  {
    id: 7,
    name: 'M109帕拉丁自行榴弹炮',
    caliber: 155,
    type: '自行榴弹炮',
    mobility: '履带式',
    muzzleVelocity: 684,
    range: 30,
    barrelLength: 6.1,
    elevationRange: '-3°~+75°',
    traverseRange: '360°',
    manufacturer: 'BAE系统',
    country: '美国',
  },
  // 阿联酋火炮装备
  {
    id: 8,
    name: '阿联酋AGRAB型120毫米自行迫击炮',
    caliber: 120,
    type: '自行迫击炮',
    mobility: '轮式',
    muzzleVelocity: 325,
    range: 7.2,
    barrelLength: 1.8,
    elevationRange: '+45°~+85°',
    traverseRange: '360°',
    manufacturer: 'EDGE集团',
    country: '阿联酋',
    quantity: 87,
    ammunition: 'CS/BME1型120毫米卫星制导迫弹',
    description: '阿联酋自主研发的120毫米自行迫击炮，配备87门，具有高机动性和精确打击能力',
    compatibleAmmunition: [
      {
        id: 26,
        name: 'CS/BME1型120毫米卫星制导迫弹',
        caliber: 120,
        type: '迫击炮弹',
        guidance: '卫星制导',
      },
    ],
  },
  {
    id: 9,
    name: '阿联酋Ghannatha级快速巡逻艇（NEMO迫炮塔）',
    caliber: 120,
    type: '舰载迫击炮',
    mobility: '舰载',
    muzzleVelocity: 325,
    range: 7.2,
    barrelLength: 1.8,
    elevationRange: '+45°~+85°',
    traverseRange: '360°',
    manufacturer: 'EDGE集团',
    country: '阿联酋',
    ammunition: 'CS/BME1型120毫米卫星制导迫弹',
    description: '阿联酋Ghannatha级快速巡逻艇配备的NEMO迫炮塔，使用120毫米迫击炮',
    compatibleAmmunition: [
      {
        id: 26,
        name: 'CS/BME1型120毫米卫星制导迫弹',
        caliber: 120,
        type: '迫击炮弹',
        guidance: '卫星制导',
      },
    ],
  },
  {
    id: 10,
    name: '法国Patria AMV模块化装甲车（NEMO迫炮塔）',
    caliber: 120,
    type: '车载迫击炮',
    mobility: '轮式',
    muzzleVelocity: 325,
    range: 7.2,
    barrelLength: 1.8,
    elevationRange: '+45°~+85°',
    traverseRange: '360°',
    manufacturer: 'Patria',
    country: '阿联酋',
    ammunition: 'CS/BME1型120毫米卫星制导迫弹',
    description: '法国Patria AMV模块化装甲车配备的NEMO迫炮塔，使用120毫米迫击炮',
    compatibleAmmunition: [
      {
        id: 26,
        name: 'CS/BME1型120毫米卫星制导迫弹',
        caliber: 120,
        type: '迫击炮弹',
        guidance: '卫星制导',
      },
    ],
  },
  {
    id: 11,
    name: '塞尔维亚M69B型81毫米迫击炮',
    caliber: 81,
    type: '迫击炮',
    mobility: '牵引式',
    muzzleVelocity: 295,
    range: 5.5,
    barrelLength: 1.2,
    elevationRange: '+45°~+85°',
    traverseRange: '±5°',
    manufacturer: '塞尔维亚军械厂',
    country: '阿联酋',
    ammunition: 'CS/BME3型81毫米卫星制导迫弹',
    description: '塞尔维亚制造的81毫米迫击炮，配备卫星制导迫弹，提高打击精度',
    compatibleAmmunition: [
      {
        id: 27,
        name: 'CS/BME3型81毫米卫星制导迫弹',
        caliber: 81,
        type: '迫击炮弹',
        guidance: '卫星制导',
      },
    ],
  },
  {
    id: 12,
    name: '塞尔维亚M69A型82毫米迫击炮',
    caliber: 82,
    type: '迫击炮',
    mobility: '牵引式',
    muzzleVelocity: 300,
    range: 5.8,
    barrelLength: 1.3,
    elevationRange: '+45°~+85°',
    traverseRange: '±5°',
    manufacturer: '塞尔维亚军械厂',
    country: '阿联酋',
    ammunition: 'CS/BME4型82毫米卫星制导迫弹',
    description: '塞尔维亚制造的82毫米迫击炮，配备卫星制导迫弹，增强火力支援能力',
    compatibleAmmunition: [
      {
        id: 28,
        name: 'CS/BME4型82毫米卫星制导迫弹',
        caliber: 82,
        type: '迫击炮弹',
        guidance: '卫星制导',
      },
    ],
  },
  {
    id: 13,
    name: '英国L118型105毫米轻型榴弹炮',
    caliber: 105,
    type: '轻型榴弹炮',
    mobility: '牵引式',
    muzzleVelocity: 712,
    range: 17.2,
    barrelLength: 4.2,
    elevationRange: '-5°~+70°',
    traverseRange: '±5°',
    manufacturer: 'BAE系统',
    country: '阿联酋',
    ammunition: '', // 表格中弹药为空
    description: '英国制造的105毫米轻型榴弹炮，具有重量轻、机动性强的特点',
  },
  {
    id: 14,
    name: '国产59式130毫米加农炮',
    caliber: 130,
    type: '加农炮',
    mobility: '牵引式',
    muzzleVelocity: 930,
    range: 27.5,
    barrelLength: 6.0,
    elevationRange: '-2°~+45°',
    traverseRange: '±25°',
    manufacturer: '中国北方工业公司',
    country: '阿联酋',
    ammunition: '', // 表格中弹药为空
    description: '中国制造的130毫米加农炮，具有射程远、威力大的特点',
  },
  {
    id: 15,
    name: '美国M109式155毫米加榴炮',
    caliber: 155,
    type: '自行榴弹炮',
    mobility: '履带式',
    muzzleVelocity: 684,
    range: 30,
    barrelLength: 6.1,
    elevationRange: '-3°~+75°',
    traverseRange: '360°',
    manufacturer: 'BAE系统',
    country: '阿联酋',
    ammunition: 'GP1型155毫米激光末制导炮弹、GP11型155毫米卫星制导炮弹',
    description: '美国制造的155毫米自行榴弹炮，配备精确制导炮弹，提高打击精度',
    compatibleAmmunition: [
      {
        id: 29,
        name: 'GP1型155毫米激光末制导炮弹',
        caliber: 155,
        type: '榴弹',
        guidance: '激光末制导',
      },
      {
        id: 30,
        name: 'GP11型155毫米卫星制导炮弹',
        caliber: 155,
        type: '榴弹',
        guidance: '卫星制导',
      },
    ],
  },
  {
    id: 16,
    name: '南非G6式155毫米车载加榴炮',
    caliber: 155,
    type: '车载榴弹炮',
    mobility: '轮式',
    muzzleVelocity: 900,
    range: 42,
    barrelLength: 7.5,
    elevationRange: '-5°~+75°',
    traverseRange: '±40°',
    manufacturer: '丹尼尔公司',
    country: '阿联酋',
    ammunition: 'GP1型155毫米激光末制导炮弹、GP11型155毫米卫星制导炮弹',
    description: '南非制造的155毫米车载榴弹炮，具有高机动性和远射程',
    compatibleAmmunition: [
      {
        id: 29,
        name: 'GP1型155毫米激光末制导炮弹',
        caliber: 155,
        type: '榴弹',
        guidance: '激光末制导',
      },
      {
        id: 30,
        name: 'GP11型155毫米卫星制导炮弹',
        caliber: 155,
        type: '榴弹',
        guidance: '卫星制导',
      },
    ],
  },
  {
    id: 17,
    name: '国产AH4型155毫米轻型榴弹炮',
    caliber: 155,
    type: '轻型榴弹炮',
    mobility: '牵引式',
    muzzleVelocity: 820,
    range: 25,
    barrelLength: 6.0,
    elevationRange: '-5°~+70°',
    traverseRange: '±25°',
    manufacturer: '中国北方工业公司',
    country: '阿联酋',
    ammunition: 'GP1型155毫米激光末制导炮弹、GP11型155毫米卫星制导炮弹',
    description: '中国制造的155毫米轻型榴弹炮，重量轻、机动性强',
    compatibleAmmunition: [
      {
        id: 29,
        name: 'GP1型155毫米激光末制导炮弹',
        caliber: 155,
        type: '榴弹',
        guidance: '激光末制导',
      },
      {
        id: 30,
        name: 'GP11型155毫米卫星制导炮弹',
        caliber: 155,
        type: '榴弹',
        guidance: '卫星制导',
      },
    ],
  },
  {
    id: 18,
    name: '国产SH15型155毫米车载加榴炮',
    caliber: 155,
    type: '车载榴弹炮',
    mobility: '轮式',
    muzzleVelocity: 900,
    range: 40,
    barrelLength: 7.5,
    elevationRange: '-5°~+70°',
    traverseRange: '±30°',
    manufacturer: '中国北方工业公司',
    country: '阿联酋',
    ammunition: 'GP1型155毫米激光末制导炮弹、GP11型155毫米卫星制导炮弹',
    description: '中国制造的155毫米车载榴弹炮，具有高机动性和精确打击能力',
  },
  // 新增中国火炮产品
  {
    id: 19,
    name: 'PLZ-07自行榴弹炮',
    caliber: 122,
    type: '自行榴弹炮',
    mobility: '履带式',
    muzzleVelocity: 690,
    range: 22,
    barrelLength: 4.8,
    elevationRange: '-3°~+70°',
    traverseRange: '360°',
    manufacturer: '中国北方工业公司',
    country: '中国',
  },
  {
    id: 20,
    name: 'PHL-03远程火箭炮',
    caliber: 300,
    type: '火箭炮',
    mobility: '轮式',
    muzzleVelocity: 1200,
    range: 150,
    barrelLength: 7.2,
    elevationRange: '0°~+55°',
    traverseRange: '±30°',
    manufacturer: '中国航天科工集团',
    country: '中国',
  },
  {
    id: 21,
    name: 'PCP-001迫击炮',
    caliber: 120,
    type: '迫击炮',
    mobility: '轮式',
    muzzleVelocity: 325,
    range: 8.5,
    barrelLength: 1.8,
    elevationRange: '45°~+80°',
    traverseRange: '360°',
    manufacturer: '中国北方工业公司',
    country: '中国',
  },
  // 新增美国火炮产品
  {
    id: 22,
    name: 'M142海马斯火箭炮',
    caliber: 227,
    type: '火箭炮',
    mobility: '轮式',
    muzzleVelocity: 1000,
    range: 70,
    barrelLength: 4.0,
    elevationRange: '0°~+60°',
    traverseRange: '±90°',
    manufacturer: '洛克希德·马丁',
    country: '美国',
  },
  {
    id: 23,
    name: 'M120迫击炮',
    caliber: 120,
    type: '迫击炮',
    mobility: '牵引式',
    muzzleVelocity: 325,
    range: 7.2,
    barrelLength: 1.8,
    elevationRange: '45°~+80°',
    traverseRange: '360°',
    manufacturer: '通用动力',
    country: '美国',
  },
  // 新增俄罗斯火炮产品
  {
    id: 24,
    name: 'BM-21冰雹火箭炮',
    caliber: 122,
    type: '火箭炮',
    mobility: '轮式',
    muzzleVelocity: 690,
    range: 20,
    barrelLength: 3.0,
    elevationRange: '0°~+55°',
    traverseRange: '±70°',
    manufacturer: '乌拉尔机车厂',
    country: '俄罗斯',
  },
  {
    id: 25,
    name: '2S23诺娜迫击炮',
    caliber: 120,
    type: '迫击炮',
    mobility: '轮式',
    muzzleVelocity: 325,
    range: 8.8,
    barrelLength: 1.8,
    elevationRange: '45°~+80°',
    traverseRange: '360°',
    manufacturer: '乌拉尔机车厂',
    country: '俄罗斯',
  },
  // 新增德国火炮产品
  {
    id: 26,
    name: 'MARS火箭炮',
    caliber: 227,
    type: '火箭炮',
    mobility: '履带式',
    muzzleVelocity: 1000,
    range: 70,
    barrelLength: 4.0,
    elevationRange: '0°~+60°',
    traverseRange: '±90°',
    manufacturer: '克劳斯-玛菲',
    country: '德国',
  },
  {
    id: 27,
    name: 'GrW 86迫击炮',
    caliber: 120,
    type: '迫击炮',
    mobility: '牵引式',
    muzzleVelocity: 325,
    range: 6.5,
    barrelLength: 1.8,
    elevationRange: '45°~+80°',
    traverseRange: '360°',
    manufacturer: '莱茵金属',
    country: '德国',
  },
  // 新增法国火炮产品
  {
    id: 28,
    name: 'LRU火箭炮',
    caliber: 227,
    type: '火箭炮',
    mobility: '轮式',
    muzzleVelocity: 1000,
    range: 70,
    barrelLength: 4.0,
    elevationRange: '0°~+60°',
    traverseRange: '±90°',
    manufacturer: '奈克斯特',
    country: '法国',
  },
  {
    id: 29,
    name: 'RT-61迫击炮',
    caliber: 120,
    type: '迫击炮',
    mobility: '牵引式',
    muzzleVelocity: 325,
    range: 8.1,
    barrelLength: 1.8,
    elevationRange: '45°~+80°',
    traverseRange: '360°',
    manufacturer: '奈克斯特',
    country: '法国',
  },
  // 新增英国火炮产品
  {
    id: 30,
    name: 'AS-90自行榴弹炮',
    caliber: 155,
    type: '自行榴弹炮',
    mobility: '履带式',
    muzzleVelocity: 827,
    range: 40,
    barrelLength: 6.4,
    elevationRange: '-5°~+70°',
    traverseRange: '360°',
    manufacturer: 'BAE系统',
    country: '英国',
  },
  {
    id: 31,
    name: 'L16迫击炮',
    caliber: 81,
    type: '迫击炮',
    mobility: '牵引式',
    muzzleVelocity: 225,
    range: 5.6,
    barrelLength: 1.3,
    elevationRange: '45°~+80°',
    traverseRange: '360°',
    manufacturer: '皇家军械厂',
    country: '英国',
  },
  // 新增以色列火炮产品
  {
    id: 32,
    name: 'Soltam M-71榴弹炮',
    caliber: 155,
    type: '牵引榴弹炮',
    mobility: '牵引式',
    muzzleVelocity: 827,
    range: 40,
    barrelLength: 6.4,
    elevationRange: '-5°~+70°',
    traverseRange: '±25°',
    manufacturer: '索尔塔姆',
    country: '以色列',
  },
  {
    id: 33,
    name: 'Cardom迫击炮',
    caliber: 120,
    type: '迫击炮',
    mobility: '轮式',
    muzzleVelocity: 325,
    range: 7.2,
    barrelLength: 1.8,
    elevationRange: '45°~+80°',
    traverseRange: '360°',
    manufacturer: '索尔塔姆',
    country: '以色列',
  },
  // 新增韩国火炮产品
  {
    id: 34,
    name: 'K136古鲁火箭炮',
    caliber: 130,
    type: '火箭炮',
    mobility: '轮式',
    muzzleVelocity: 750,
    range: 23,
    barrelLength: 2.5,
    elevationRange: '0°~+55°',
    traverseRange: '±90°',
    manufacturer: '韩华系统',
    country: '韩国',
  },
  {
    id: 35,
    name: 'KM29迫击炮',
    caliber: 81,
    type: '迫击炮',
    mobility: '牵引式',
    muzzleVelocity: 225,
    range: 5.6,
    barrelLength: 1.3,
    elevationRange: '45°~+80°',
    traverseRange: '360°',
    manufacturer: '韩华系统',
    country: '韩国',
  },
  {
    id: 36,
    name: '国产SH15型155毫米车载加榴炮',
    caliber: 155,
    type: '车载榴弹炮',
    mobility: '轮式',
    muzzleVelocity: 900,
    range: 40,
    barrelLength: 7.5,
    elevationRange: '-5°~+70°',
    traverseRange: '±30°',
    manufacturer: '中国北方工业公司',
    country: '阿联酋',
    ammunition: 'GP1型155毫米激光末制导炮弹、GP11型155毫米卫星制导炮弹',
    description: '中国制造的155毫米车载榴弹炮，具有高机动性和精确打击能力',
    compatibleAmmunition: [
      {
        id: 29,
        name: 'GP1型155毫米激光末制导炮弹',
        caliber: 155,
        type: '榴弹',
        guidance: '激光末制导',
      },
      {
        id: 30,
        name: 'GP11型155毫米卫星制导炮弹',
        caliber: 155,
        type: '榴弹',
        guidance: '卫星制导',
      },
    ],
  },
];

// 获取类型颜色
const getTypeColor = (type: string) => {
  switch (type) {
    case '自行榴弹炮':
      return 'blue';
    case '牵引榴弹炮':
      return 'green';
    case '火箭炮':
      return 'red';
    default:
      return 'gray';
  }
};

// 获取运动方式颜色
const getMobilityColor = (mobility: string) => {
  switch (mobility) {
    case '履带式':
      return 'orange';
    case '轮式':
      return 'purple';
    case '牵引式':
      return 'cyan';
    default:
      return 'gray';
  }
};

// 火炮检索列配置
export const artilleryColumns: SearchColumn[] = [
  {
    title: '火炮名称',
    dataIndex: 'name',
    width: 200,
    render: value => <Text bold>{value}</Text>,
  },
  {
    title: '口径',
    dataIndex: 'caliber',
    width: 80,
    render: value => `${value}mm`,
    sorter: (a: any, b: any) => a.caliber - b.caliber,
  },
  {
    title: '类型',
    dataIndex: 'type',
    width: 120,
    render: (value: string) => <Tag color={getTypeColor(value)}>{value}</Tag>,
  },
  {
    title: '运动方式',
    dataIndex: 'mobility',
    width: 100,
    render: (value: string) => <Tag color={getMobilityColor(value)}>{value}</Tag>,
  },
  {
    title: '初速',
    dataIndex: 'muzzleVelocity',
    width: 100,
    render: value => `${value}m/s`,
    sorter: (a: any, b: any) => a.muzzleVelocity - b.muzzleVelocity,
  },
  {
    title: '射程',
    dataIndex: 'range',
    width: 80,
    render: value => `${value}km`,
    sorter: (a: any, b: any) => a.range - b.range,
  },
  {
    title: '身管长度',
    dataIndex: 'barrelLength',
    width: 100,
    render: value => `${value}m`,
    sorter: (a: any, b: any) => a.barrelLength - b.barrelLength,
  },
  {
    title: '厂商',
    dataIndex: 'manufacturer',
    width: 160,
    ellipsis: true,
  },
  {
    title: '国家',
    dataIndex: 'country',
    width: 80,
    render: value => <Tag color="orange">{value}</Tag>,
  },
];

// 搜索字段配置
export const artillerySearchFields = ['name', 'type', 'mobility', 'manufacturer', 'country'];

// 搜索建议
export const artillerySuggestions = [
  '自行榴弹炮',
  '牵引榴弹炮',
  '履带式',
  '轮式',
  '155mm',
  '152mm',
  '中国',
  '美国',
  '德国',
  'PLZ-05',
  'M777',
  'PzH 2000',
  'CAESAR',
];
