// 国家数据
export const countryData = [
  {
    id: 1,
    name: '中国',
    nameEn: 'China',
    region: '亚洲',
    products: ['红箭-12导弹', 'PLZ-05自行榴弹炮', '东风系列导弹'],
    manufacturers: ['中国兵器工业集团', '中国航天科技集团'],
  },
  {
    id: 2,
    name: '美国',
    nameEn: 'United States',
    region: '北美洲',
    products: ['地狱火导弹', 'M777榴弹炮', '战斧巡航导弹'],
    manufacturers: ['洛克希德·马丁', '雷神公司', '通用动力'],
  },
  {
    id: 3,
    name: '俄罗斯',
    nameEn: 'Russia',
    region: '欧洲',
    products: ['伊斯坎德尔导弹', '姆斯塔河榴弹炮', 'S-400防空系统'],
    manufacturers: ['俄罗斯战术导弹公司', '乌拉尔机车厂'],
  },
  {
    id: 4,
    name: '德国',
    nameEn: 'Germany',
    region: '欧洲',
    products: ['PzH 2000自行榴弹炮', '豹2坦克', 'IRIS-T导弹'],
    manufacturers: ['莱茵金属', '克劳斯-玛菲'],
  },
  {
    id: 5,
    name: '法国',
    nameEn: 'France',
    region: '欧洲',
    products: ['CAESAR自行榴弹炮', '飞鱼导弹', 'MICA导弹'],
    manufacturers: ['奈克斯特', 'MBDA'],
  },
  {
    id: 6,
    name: '英国',
    nameEn: 'United Kingdom',
    region: '欧洲',
    products: ['挑战者2坦克', '海标枪导弹', '暴风战斗机'],
    manufacturers: ['BAE系统', '劳斯莱斯'],
  },
  {
    id: 7,
    name: '以色列',
    nameEn: 'Israel',
    region: '亚洲',
    products: ['铁穹防空系统', '梅卡瓦坦克', '长钉导弹'],
    manufacturers: ['拉斐尔', '以色列航空工业'],
  },
  {
    id: 8,
    name: '韩国',
    nameEn: 'South Korea',
    region: '亚洲',
    products: ['K9雷鸣自行榴弹炮', 'K2黑豹坦克', '玄武导弹'],
    manufacturers: ['韩华系统', '现代重工'],
  },
  {
    id: 9,
    name: '阿联酋',
    nameEn: 'United Arab Emirates',
    region: '亚洲',
    products: [
      'Al Tariq导弹',
      'Nimr装甲车',
      'Al Fattan战斗机',
      'AGRAB型120毫米自行迫击炮',
      'Ghannatha级快速巡逻艇',
    ],
    manufacturers: ['阿联酋国防工业公司', '阿联酋航空工业集团', 'EDGE集团'],
    armedForces: {
      total: 63000,
      army: 44000,
      navy: 2500,
      airForce: 4000,
      presidentialGuard: 12000,
    },
    threats: ['伊朗', '胡塞武装'],
    conflicts: ['也门冲突', '霍尔木兹海峡争端'],
    foreignPolicy: {
      allies: ['美国', '法国', '韩国', '中国', '沙特阿拉伯'],
      relations: {
        iran: '敌对',
        israel: '友好（2020年《亚伯拉罕协议》）',
        yemen: '参与也门冲突（2015-2019）',
        palestine: '支持',
      },
    },
    defenseIndustry: {
      mainCompany: 'EDGE集团',
      capabilities: ['制式迫弹生产', '陆地无人装备研制', '空中无人装备研制'],
      status: '2019年成立，收入增长显著，国际认可度待提升',
    },
    artilleryEquipment: {
      mortars: [
        {
          caliber: 81,
          name: '塞尔维亚M69B型81毫米迫击炮',
          ammunition: 'CS/BME3型81毫米卫星制导迫弹',
        },
        {
          caliber: 82,
          name: '塞尔维亚M69A型82毫米迫击炮',
          ammunition: 'CS/BME4型82毫米卫星制导迫弹',
        },
        {
          caliber: 120,
          name: '阿联酋AGRAB型120毫米自行迫击炮（87门）',
          ammunition: 'CS/BME1型120毫米卫星制导迫弹',
        },
        {
          caliber: 120,
          name: '阿联酋Ghannatha级快速巡逻艇（NEMO迫炮塔）',
          ammunition: 'CS/BME1型120毫米卫星制导迫弹',
        },
        {
          caliber: 120,
          name: '法国Patria AMV模块化装甲车（NEMO迫炮塔）',
          ammunition: 'CS/BME1型120毫米卫星制导迫弹',
        },
      ],
      howitzers: [
        { caliber: 105, name: '英国L118型105毫米轻型榴弹炮', ammunition: '' },
        { caliber: 130, name: '国产59式130毫米加农炮', ammunition: '' },
        {
          caliber: 155,
          name: '美国M109式155毫米加榴炮',
          ammunition: 'GP1型155毫米激光末制导炮弹、GP11型155毫米卫星制导炮弹',
        },
        {
          caliber: 155,
          name: '南非G6式155毫米车载加榴炮',
          ammunition: 'GP1型155毫米激光末制导炮弹、GP11型155毫米卫星制导炮弹',
        },
        {
          caliber: 155,
          name: '国产AH4型155毫米轻型榴弹炮',
          ammunition: 'GP1型155毫米激光末制导炮弹、GP11型155毫米卫星制导炮弹',
        },
        {
          caliber: 155,
          name: '国产SH15型155毫米车载加榴炮',
          ammunition: 'GP1型155毫米激光末制导炮弹、GP11型155毫米卫星制导炮弹',
        },
      ],
    },
  },
  {
    id: 10,
    name: '日本',
    nameEn: 'Japan',
    region: '亚洲',
    products: ['12式地对舰导弹', '99式自行榴弹炮', 'F-2战斗机'],
    manufacturers: ['三菱重工', '川崎重工', '富士重工'],
  },
  {
    id: 11,
    name: '印度',
    nameEn: 'India',
    region: '亚洲',
    products: ['布拉莫斯导弹', 'K9 Vajra榴弹炮', '阿琼坦克'],
    manufacturers: ['印度国防研究与发展组织', '巴拉特电子'],
  },
  {
    id: 12,
    name: '新加坡',
    nameEn: 'Singapore',
    region: '亚洲',
    products: ['Spike导弹', 'Primus榴弹炮', 'Hunter装甲车'],
    manufacturers: ['新加坡科技工程', '新加坡国防科技局'],
  },
  {
    id: 13,
    name: '泰国',
    nameEn: 'Thailand',
    region: '亚洲',
    products: ['DTI-1导弹', 'M109榴弹炮', 'VT-4坦克'],
    manufacturers: ['泰国国防工业组织', '泰国皇家陆军'],
  },
  {
    id: 14,
    name: '印度尼西亚',
    nameEn: 'Indonesia',
    region: '亚洲',
    products: ['R-Han 122火箭弹', 'M109榴弹炮', 'Leopard 2坦克'],
    manufacturers: ['印尼国防工业', '印尼航空航天'],
  },
  {
    id: 15,
    name: '马来西亚',
    nameEn: 'Malaysia',
    region: '亚洲',
    products: ['Al Tariq导弹', 'G5榴弹炮', 'PT-91M坦克'],
    manufacturers: ['马来西亚国防工业', '马来西亚航空航天'],
  },
  {
    id: 16,
    name: '越南',
    nameEn: 'Vietnam',
    region: '亚洲',
    products: ['BM-21火箭炮', 'D-30榴弹炮', 'T-90S坦克'],
    manufacturers: ['越南国防工业', '越南军事技术学院'],
  },
  {
    id: 17,
    name: '菲律宾',
    nameEn: 'Philippines',
    region: '亚洲',
    products: ['Spike导弹', 'M101榴弹炮', 'M113装甲车'],
    manufacturers: ['菲律宾国防工业', '菲律宾陆军'],
  },
  {
    id: 18,
    name: '孟加拉国',
    nameEn: 'Bangladesh',
    region: '亚洲',
    products: ['MBT-2000坦克', 'M101榴弹炮', 'Type 81火箭炮'],
    manufacturers: ['孟加拉国国防工业', '孟加拉国陆军'],
  },
  {
    id: 19,
    name: '巴基斯坦',
    nameEn: 'Pakistan',
    region: '亚洲',
    products: ['哈塔夫导弹', 'M109榴弹炮', 'Al-Khalid坦克'],
    manufacturers: ['巴基斯坦军械厂', '巴基斯坦航空工业'],
  },
  {
    id: 20,
    name: '土耳其',
    nameEn: 'Turkey',
    region: '亚洲',
    products: ['Javelin导弹', 'T-155榴弹炮', 'Altay坦克'],
    manufacturers: ['土耳其国防工业', '土耳其航空航天'],
  },
  {
    id: 21,
    name: '沙特阿拉伯',
    nameEn: 'Saudi Arabia',
    region: '亚洲',
    products: ['Al Tariq导弹', 'M109榴弹炮', 'M1A2坦克'],
    manufacturers: ['沙特国防工业', '沙特军事工业'],
  },
  {
    id: 22,
    name: '伊朗',
    nameEn: 'Iran',
    region: '亚洲',
    products: ['Fateh-110导弹', 'Raad-2榴弹炮', 'Karrar坦克'],
    manufacturers: ['伊朗国防工业', '伊朗航空航天'],
  },
  {
    id: 23,
    name: '伊拉克',
    nameEn: 'Iraq',
    region: '亚洲',
    products: ['Al Fao榴弹炮', 'T-72坦克', 'BMP-1装甲车'],
    manufacturers: ['伊拉克国防工业', '伊拉克陆军'],
  },
  // 欧洲其他国家
  {
    id: 24,
    name: '荷兰',
    nameEn: 'Netherlands',
    region: '欧洲',
    products: ['PzH 2000榴弹炮', 'Leopard 2坦克', 'Patriot防空系统'],
    manufacturers: ['荷兰皇家陆军', '荷兰国防工业'],
  },
  {
    id: 25,
    name: '瑞士',
    nameEn: 'Switzerland',
    region: '欧洲',
    products: ['M109榴弹炮', 'Leopard 2坦克', 'Rapier防空系统'],
    manufacturers: ['瑞士国防工业', '瑞士陆军'],
  },
  {
    id: 26,
    name: '瑞典',
    nameEn: 'Sweden',
    region: '欧洲',
    products: ['Archer榴弹炮', 'Strv 122坦克', 'RBS 70防空导弹'],
    manufacturers: ['博福斯', '萨博', '瑞典国防工业'],
  },
  {
    id: 27,
    name: '挪威',
    nameEn: 'Norway',
    region: '欧洲',
    products: ['M109榴弹炮', 'Leopard 2坦克', 'NASAMS防空系统'],
    manufacturers: ['挪威国防工业', '挪威陆军'],
  },
  {
    id: 28,
    name: '丹麦',
    nameEn: 'Denmark',
    region: '欧洲',
    products: ['M109榴弹炮', 'Leopard 2坦克', 'I-Hawk防空系统'],
    manufacturers: ['丹麦国防工业', '丹麦陆军'],
  },
  {
    id: 29,
    name: '芬兰',
    nameEn: 'Finland',
    region: '欧洲',
    products: ['K9榴弹炮', 'Leopard 2坦克', 'NASAMS防空系统'],
    manufacturers: ['芬兰国防工业', '芬兰陆军'],
  },
  {
    id: 30,
    name: '波兰',
    nameEn: 'Poland',
    region: '欧洲',
    products: ['K9榴弹炮', 'Leopard 2坦克', 'Patriot防空系统'],
    manufacturers: ['波兰国防工业', '波兰陆军'],
  },
  {
    id: 31,
    name: '捷克',
    nameEn: 'Czech Republic',
    region: '欧洲',
    products: ['Dana榴弹炮', 'T-72坦克', 'Kub防空系统'],
    manufacturers: ['捷克国防工业', '捷克陆军'],
  },
  {
    id: 32,
    name: '奥地利',
    nameEn: 'Austria',
    region: '欧洲',
    products: ['M109榴弹炮', 'Leopard 2坦克', 'Mistral防空导弹'],
    manufacturers: ['奥地利国防工业', '奥地利陆军'],
  },
  {
    id: 33,
    name: '比利时',
    nameEn: 'Belgium',
    region: '欧洲',
    products: ['M109榴弹炮', 'Leopard 1坦克', 'Mistral防空导弹'],
    manufacturers: ['比利时国防工业', '比利时陆军'],
  },
  {
    id: 34,
    name: '爱尔兰',
    nameEn: 'Ireland',
    region: '欧洲',
    products: ['L118榴弹炮', 'FV101装甲车', 'Javelin防空导弹'],
    manufacturers: ['爱尔兰国防工业', '爱尔兰陆军'],
  },
  {
    id: 35,
    name: '葡萄牙',
    nameEn: 'Portugal',
    region: '欧洲',
    products: ['M109榴弹炮', 'M60坦克', 'Mistral防空导弹'],
    manufacturers: ['葡萄牙国防工业', '葡萄牙陆军'],
  },
  {
    id: 36,
    name: '希腊',
    nameEn: 'Greece',
    region: '欧洲',
    products: ['M109榴弹炮', 'Leopard 2坦克', 'Patriot防空系统'],
    manufacturers: ['希腊国防工业', '希腊陆军'],
  },
  {
    id: 37,
    name: '匈牙利',
    nameEn: 'Hungary',
    region: '欧洲',
    products: ['M109榴弹炮', 'T-72坦克', 'Kub防空系统'],
    manufacturers: ['匈牙利国防工业', '匈牙利陆军'],
  },
  // 美洲其他国家
  {
    id: 38,
    name: '加拿大',
    nameEn: 'Canada',
    region: '北美洲',
    products: ['M777榴弹炮', 'Leopard 2坦克', 'Patriot防空系统'],
    manufacturers: ['加拿大国防工业', '加拿大陆军'],
  },
  {
    id: 39,
    name: '墨西哥',
    nameEn: 'Mexico',
    region: '北美洲',
    products: ['M101榴弹炮', 'DN-V装甲车', 'RBS 70防空导弹'],
    manufacturers: ['墨西哥国防工业', '墨西哥陆军'],
  },
  {
    id: 40,
    name: '巴西',
    nameEn: 'Brazil',
    region: '南美洲',
    products: ['Astros火箭炮', 'EE-T2坦克', 'Mistral防空导弹'],
    manufacturers: ['巴西国防工业', '巴西陆军'],
  },
  {
    id: 41,
    name: '阿根廷',
    nameEn: 'Argentina',
    region: '南美洲',
    products: ['VCA 155榴弹炮', 'TAM坦克', 'RBS 70防空导弹'],
    manufacturers: ['阿根廷国防工业', '阿根廷陆军'],
  },
  {
    id: 42,
    name: '智利',
    nameEn: 'Chile',
    region: '南美洲',
    products: ['M109榴弹炮', 'Leopard 2坦克', 'Mistral防空导弹'],
    manufacturers: ['智利国防工业', '智利陆军'],
  },
  {
    id: 43,
    name: '哥伦比亚',
    nameEn: 'Colombia',
    region: '南美洲',
    products: ['M101榴弹炮', 'M60坦克', 'RBS 70防空导弹'],
    manufacturers: ['哥伦比亚国防工业', '哥伦比亚陆军'],
  },
  {
    id: 44,
    name: '秘鲁',
    nameEn: 'Peru',
    region: '南美洲',
    products: ['M101榴弹炮', 'T-90坦克', 'Mistral防空导弹'],
    manufacturers: ['秘鲁国防工业', '秘鲁陆军'],
  },
  {
    id: 45,
    name: '委内瑞拉',
    nameEn: 'Venezuela',
    region: '南美洲',
    products: ['M101榴弹炮', 'T-72坦克', 'S-300防空系统'],
    manufacturers: ['委内瑞拉国防工业', '委内瑞拉陆军'],
  },
  {
    id: 46,
    name: '乌拉圭',
    nameEn: 'Uruguay',
    region: '南美洲',
    products: ['M101榴弹炮', 'M41坦克', 'RBS 70防空导弹'],
    manufacturers: ['乌拉圭国防工业', '乌拉圭陆军'],
  },
  {
    id: 47,
    name: '厄瓜多尔',
    nameEn: 'Ecuador',
    region: '南美洲',
    products: ['M101榴弹炮', 'Leopard 1坦克', 'Mistral防空导弹'],
    manufacturers: ['厄瓜多尔国防工业', '厄瓜多尔陆军'],
  },
  {
    id: 48,
    name: '玻利维亚',
    nameEn: 'Bolivia',
    region: '南美洲',
    products: ['M101榴弹炮', 'SK-105坦克', 'RBS 70防空导弹'],
    manufacturers: ['玻利维亚国防工业', '玻利维亚陆军'],
  },
  {
    id: 49,
    name: '巴拉圭',
    nameEn: 'Paraguay',
    region: '南美洲',
    products: ['M101榴弹炮', 'M4谢尔曼坦克', 'Mistral防空导弹'],
    manufacturers: ['巴拉圭国防工业', '巴拉圭陆军'],
  },
  // 非洲其他国家
  {
    id: 50,
    name: '南非',
    nameEn: 'South Africa',
    region: '非洲',
    products: ['G6榴弹炮', 'Olifant坦克', 'Crotale防空系统'],
    manufacturers: ['南非国防工业', '南非陆军'],
  },
  {
    id: 51,
    name: '埃及',
    nameEn: 'Egypt',
    region: '非洲',
    products: ['M109榴弹炮', 'M1A1坦克', 'Patriot防空系统'],
    manufacturers: ['埃及国防工业', '埃及陆军'],
  },
  {
    id: 52,
    name: '尼日利亚',
    nameEn: 'Nigeria',
    region: '非洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['尼日利亚国防工业', '尼日利亚陆军'],
  },
  {
    id: 53,
    name: '埃塞俄比亚',
    nameEn: 'Ethiopia',
    region: '非洲',
    products: ['M101榴弹炮', 'T-72坦克', 'RBS 70防空导弹'],
    manufacturers: ['埃塞俄比亚国防工业', '埃塞俄比亚陆军'],
  },
  {
    id: 54,
    name: '肯尼亚',
    nameEn: 'Kenya',
    region: '非洲',
    products: ['M101榴弹炮', 'Vickers坦克', 'Mistral防空导弹'],
    manufacturers: ['肯尼亚国防工业', '肯尼亚陆军'],
  },
  {
    id: 55,
    name: '坦桑尼亚',
    nameEn: 'Tanzania',
    region: '非洲',
    products: ['M101榴弹炮', 'T-72坦克', 'RBS 70防空导弹'],
    manufacturers: ['坦桑尼亚国防工业', '坦桑尼亚陆军'],
  },
  {
    id: 56,
    name: '乌干达',
    nameEn: 'Uganda',
    region: '非洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['乌干达国防工业', '乌干达陆军'],
  },
  {
    id: 57,
    name: '加纳',
    nameEn: 'Ghana',
    region: '非洲',
    products: ['M101榴弹炮', 'M48坦克', 'RBS 70防空导弹'],
    manufacturers: ['加纳国防工业', '加纳陆军'],
  },
  {
    id: 58,
    name: '科特迪瓦',
    nameEn: 'Ivory Coast',
    region: '非洲',
    products: ['M101榴弹炮', 'T-55坦克', 'Mistral防空导弹'],
    manufacturers: ['科特迪瓦国防工业', '科特迪瓦陆军'],
  },
  {
    id: 59,
    name: '塞内加尔',
    nameEn: 'Senegal',
    region: '非洲',
    products: ['M101榴弹炮', 'M48坦克', 'RBS 70防空导弹'],
    manufacturers: ['塞内加尔国防工业', '塞内加尔陆军'],
  },
  {
    id: 60,
    name: '马里',
    nameEn: 'Mali',
    region: '非洲',
    products: ['M101榴弹炮', 'T-55坦克', 'Mistral防空导弹'],
    manufacturers: ['马里国防工业', '马里陆军'],
  },
  // 大洋洲其他国家
  {
    id: 61,
    name: '澳大利亚',
    nameEn: 'Australia',
    region: '大洋洲',
    products: ['M777榴弹炮', 'M1A2坦克', 'Patriot防空系统'],
    manufacturers: ['澳大利亚国防工业', '澳大利亚陆军'],
  },
  {
    id: 62,
    name: '新西兰',
    nameEn: 'New Zealand',
    region: '大洋洲',
    products: ['L118榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['新西兰国防工业', '新西兰陆军'],
  },
  {
    id: 63,
    name: '斐济',
    nameEn: 'Fiji',
    region: '大洋洲',
    products: ['M101榴弹炮', 'M113装甲车', 'RBS 70防空导弹'],
    manufacturers: ['斐济国防工业', '斐济陆军'],
  },
  {
    id: 64,
    name: '巴布亚新几内亚',
    nameEn: 'Papua New Guinea',
    region: '大洋洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['巴布亚新几内亚国防工业', '巴布亚新几内亚陆军'],
  },
  // 添加更多国家
  {
    id: 65,
    name: '新喀里多尼亚',
    nameEn: 'New Caledonia',
    region: '大洋洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['新喀里多尼亚国防工业', '新喀里多尼亚陆军'],
  },
  {
    id: 66,
    name: '法属波利尼西亚',
    nameEn: 'French Polynesia',
    region: '大洋洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['法属波利尼西亚国防工业', '法属波利尼西亚陆军'],
  },
  {
    id: 67,
    name: '瓦努阿图',
    nameEn: 'Vanuatu',
    region: '大洋洲',
    products: ['M101榴弹炮', 'M113装甲车', 'RBS 70防空导弹'],
    manufacturers: ['瓦努阿图国防工业', '瓦努阿图陆军'],
  },
  {
    id: 68,
    name: '所罗门群岛',
    nameEn: 'Solomon Islands',
    region: '大洋洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['所罗门群岛国防工业', '所罗门群岛陆军'],
  },
  {
    id: 69,
    name: '汤加',
    nameEn: 'Tonga',
    region: '大洋洲',
    products: ['M101榴弹炮', 'M113装甲车', 'RBS 70防空导弹'],
    manufacturers: ['汤加国防工业', '汤加陆军'],
  },
  {
    id: 70,
    name: '萨摩亚',
    nameEn: 'Samoa',
    region: '大洋洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['萨摩亚国防工业', '萨摩亚陆军'],
  },
  {
    id: 71,
    name: '基里巴斯',
    nameEn: 'Kiribati',
    region: '大洋洲',
    products: ['M101榴弹炮', 'M113装甲车', 'RBS 70防空导弹'],
    manufacturers: ['基里巴斯国防工业', '基里巴斯陆军'],
  },
  {
    id: 72,
    name: '图瓦卢',
    nameEn: 'Tuvalu',
    region: '大洋洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['图瓦卢国防工业', '图瓦卢陆军'],
  },
  {
    id: 73,
    name: '瑙鲁',
    nameEn: 'Nauru',
    region: '大洋洲',
    products: ['M101榴弹炮', 'M113装甲车', 'RBS 70防空导弹'],
    manufacturers: ['瑙鲁国防工业', '瑙鲁陆军'],
  },
  {
    id: 74,
    name: '帕劳',
    nameEn: 'Palau',
    region: '大洋洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['帕劳国防工业', '帕劳陆军'],
  },
  {
    id: 75,
    name: '马绍尔群岛',
    nameEn: 'Marshall Islands',
    region: '大洋洲',
    products: ['M101榴弹炮', 'M113装甲车', 'RBS 70防空导弹'],
    manufacturers: ['马绍尔群岛国防工业', '马绍尔群岛陆军'],
  },
  {
    id: 76,
    name: '密克罗尼西亚',
    nameEn: 'Micronesia',
    region: '大洋洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['密克罗尼西亚国防工业', '密克罗尼西亚陆军'],
  },
  // 添加更多欧洲国家
  {
    id: 77,
    name: '罗马尼亚',
    nameEn: 'Romania',
    region: '欧洲',
    products: ['M109榴弹炮', 'T-72坦克', 'Kub防空系统'],
    manufacturers: ['罗马尼亚国防工业', '罗马尼亚陆军'],
  },
  {
    id: 78,
    name: '保加利亚',
    nameEn: 'Bulgaria',
    region: '欧洲',
    products: ['M109榴弹炮', 'T-72坦克', 'Kub防空系统'],
    manufacturers: ['保加利亚国防工业', '保加利亚陆军'],
  },
  {
    id: 79,
    name: '克罗地亚',
    nameEn: 'Croatia',
    region: '欧洲',
    products: ['M109榴弹炮', 'M84坦克', 'Mistral防空导弹'],
    manufacturers: ['克罗地亚国防工业', '克罗地亚陆军'],
  },
  {
    id: 80,
    name: '斯洛文尼亚',
    nameEn: 'Slovenia',
    region: '欧洲',
    products: ['M109榴弹炮', 'M84坦克', 'Mistral防空导弹'],
    manufacturers: ['斯洛文尼亚国防工业', '斯洛文尼亚陆军'],
  },
  {
    id: 81,
    name: '斯洛伐克',
    nameEn: 'Slovakia',
    region: '欧洲',
    products: ['M109榴弹炮', 'T-72坦克', 'Kub防空系统'],
    manufacturers: ['斯洛伐克国防工业', '斯洛伐克陆军'],
  },
  {
    id: 82,
    name: '立陶宛',
    nameEn: 'Lithuania',
    region: '欧洲',
    products: ['M109榴弹炮', 'Leopard 2坦克', 'NASAMS防空系统'],
    manufacturers: ['立陶宛国防工业', '立陶宛陆军'],
  },
  {
    id: 83,
    name: '拉脱维亚',
    nameEn: 'Latvia',
    region: '欧洲',
    products: ['M109榴弹炮', 'Leopard 2坦克', 'NASAMS防空系统'],
    manufacturers: ['拉脱维亚国防工业', '拉脱维亚陆军'],
  },
  {
    id: 84,
    name: '爱沙尼亚',
    nameEn: 'Estonia',
    region: '欧洲',
    products: ['M109榴弹炮', 'Leopard 2坦克', 'NASAMS防空系统'],
    manufacturers: ['爱沙尼亚国防工业', '爱沙尼亚陆军'],
  },
  {
    id: 85,
    name: '卢森堡',
    nameEn: 'Luxembourg',
    region: '欧洲',
    products: ['M109榴弹炮', 'Leopard 2坦克', 'Mistral防空导弹'],
    manufacturers: ['卢森堡国防工业', '卢森堡陆军'],
  },
  {
    id: 86,
    name: '马耳他',
    nameEn: 'Malta',
    region: '欧洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['马耳他国防工业', '马耳他陆军'],
  },
  {
    id: 87,
    name: '冰岛',
    nameEn: 'Iceland',
    region: '欧洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['冰岛国防工业', '冰岛陆军'],
  },
  {
    id: 88,
    name: '阿尔巴尼亚',
    nameEn: 'Albania',
    region: '欧洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['阿尔巴尼亚国防工业', '阿尔巴尼亚陆军'],
  },
  {
    id: 89,
    name: '北马其顿',
    nameEn: 'North Macedonia',
    region: '欧洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['北马其顿国防工业', '北马其顿陆军'],
  },
  {
    id: 90,
    name: '塞尔维亚',
    nameEn: 'Serbia',
    region: '欧洲',
    products: ['M109榴弹炮', 'M84坦克', 'Kub防空系统'],
    manufacturers: ['塞尔维亚国防工业', '塞尔维亚陆军'],
  },
  {
    id: 91,
    name: '黑山',
    nameEn: 'Montenegro',
    region: '欧洲',
    products: ['M101榴弹炮', 'M84坦克', 'Mistral防空导弹'],
    manufacturers: ['黑山国防工业', '黑山陆军'],
  },
  {
    id: 92,
    name: '波斯尼亚和黑塞哥维那',
    nameEn: 'Bosnia and Herzegovina',
    region: '欧洲',
    products: ['M101榴弹炮', 'M84坦克', 'Mistral防空导弹'],
    manufacturers: ['波斯尼亚国防工业', '波斯尼亚陆军'],
  },
  {
    id: 93,
    name: '摩尔多瓦',
    nameEn: 'Moldova',
    region: '欧洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['摩尔多瓦国防工业', '摩尔多瓦陆军'],
  },
  {
    id: 94,
    name: '乌克兰',
    nameEn: 'Ukraine',
    region: '欧洲',
    products: ['M109榴弹炮', 'T-84坦克', 'S-300防空系统'],
    manufacturers: ['乌克兰国防工业', '乌克兰陆军'],
  },
  {
    id: 95,
    name: '白俄罗斯',
    nameEn: 'Belarus',
    region: '欧洲',
    products: ['M109榴弹炮', 'T-72坦克', 'S-300防空系统'],
    manufacturers: ['白俄罗斯国防工业', '白俄罗斯陆军'],
  },
  // 添加更多美洲国家
  {
    id: 96,
    name: '危地马拉',
    nameEn: 'Guatemala',
    region: '北美洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['危地马拉国防工业', '危地马拉陆军'],
  },
  {
    id: 97,
    name: '洪都拉斯',
    nameEn: 'Honduras',
    region: '北美洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['洪都拉斯国防工业', '洪都拉斯陆军'],
  },
  {
    id: 98,
    name: '萨尔瓦多',
    nameEn: 'El Salvador',
    region: '北美洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['萨尔瓦多国防工业', '萨尔瓦多陆军'],
  },
  {
    id: 99,
    name: '尼加拉瓜',
    nameEn: 'Nicaragua',
    region: '北美洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['尼加拉瓜国防工业', '尼加拉瓜陆军'],
  },
  {
    id: 100,
    name: '哥斯达黎加',
    nameEn: 'Costa Rica',
    region: '北美洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['哥斯达黎加国防工业', '哥斯达黎加陆军'],
  },
  {
    id: 101,
    name: '巴拿马',
    nameEn: 'Panama',
    region: '北美洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['巴拿马国防工业', '巴拿马陆军'],
  },
  {
    id: 102,
    name: '古巴',
    nameEn: 'Cuba',
    region: '北美洲',
    products: ['M101榴弹炮', 'T-72坦克', 'S-300防空系统'],
    manufacturers: ['古巴国防工业', '古巴陆军'],
  },
  {
    id: 103,
    name: '牙买加',
    nameEn: 'Jamaica',
    region: '北美洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['牙买加国防工业', '牙买加陆军'],
  },
  {
    id: 104,
    name: '海地',
    nameEn: 'Haiti',
    region: '北美洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['海地国防工业', '海地陆军'],
  },
  {
    id: 105,
    name: '多米尼加',
    nameEn: 'Dominican Republic',
    region: '北美洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['多米尼加国防工业', '多米尼加陆军'],
  },
  // 添加更多非洲国家
  {
    id: 106,
    name: '马达加斯加',
    nameEn: 'Madagascar',
    region: '非洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['马达加斯加国防工业', '马达加斯加陆军'],
  },
  {
    id: 107,
    name: '毛里求斯',
    nameEn: 'Mauritius',
    region: '非洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['毛里求斯国防工业', '毛里求斯陆军'],
  },
  {
    id: 108,
    name: '塞舌尔',
    nameEn: 'Seychelles',
    region: '非洲',
    products: ['M101榴弹炮', 'M113装甲车', 'RBS 70防空导弹'],
    manufacturers: ['塞舌尔国防工业', '塞舌尔陆军'],
  },
  {
    id: 109,
    name: '科摩罗',
    nameEn: 'Comoros',
    region: '非洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['科摩罗国防工业', '科摩罗陆军'],
  },
  {
    id: 110,
    name: '吉布提',
    nameEn: 'Djibouti',
    region: '非洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['吉布提国防工业', '吉布提陆军'],
  },
  {
    id: 111,
    name: '索马里',
    nameEn: 'Somalia',
    region: '非洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['索马里国防工业', '索马里陆军'],
  },
  {
    id: 112,
    name: '厄立特里亚',
    nameEn: 'Eritrea',
    region: '非洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['厄立特里亚国防工业', '厄立特里亚陆军'],
  },
  {
    id: 113,
    name: '卢旺达',
    nameEn: 'Rwanda',
    region: '非洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['卢旺达国防工业', '卢旺达陆军'],
  },
  {
    id: 114,
    name: '布隆迪',
    nameEn: 'Burundi',
    region: '非洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['布隆迪国防工业', '布隆迪陆军'],
  },
  {
    id: 115,
    name: '中非共和国',
    nameEn: 'Central African Republic',
    region: '非洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['中非共和国国防工业', '中非共和国陆军'],
  },
  {
    id: 116,
    name: '刚果共和国',
    nameEn: 'Republic of the Congo',
    region: '非洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['刚果共和国国防工业', '刚果共和国陆军'],
  },
  {
    id: 117,
    name: '刚果民主共和国',
    nameEn: 'Democratic Republic of the Congo',
    region: '非洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['刚果民主共和国国防工业', '刚果民主共和国陆军'],
  },
  {
    id: 118,
    name: '加蓬',
    nameEn: 'Gabon',
    region: '非洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['加蓬国防工业', '加蓬陆军'],
  },
  {
    id: 119,
    name: '赤道几内亚',
    nameEn: 'Equatorial Guinea',
    region: '非洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['赤道几内亚国防工业', '赤道几内亚陆军'],
  },
  {
    id: 120,
    name: '喀麦隆',
    nameEn: 'Cameroon',
    region: '非洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['喀麦隆国防工业', '喀麦隆陆军'],
  },
  {
    id: 121,
    name: '圣多美和普林西比',
    nameEn: 'Sao Tome and Principe',
    region: '非洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['圣多美和普林西比国防工业', '圣多美和普林西比陆军'],
  },
  {
    id: 122,
    name: '佛得角',
    nameEn: 'Cape Verde',
    region: '非洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['佛得角国防工业', '佛得角陆军'],
  },
  {
    id: 123,
    name: '冈比亚',
    nameEn: 'Gambia',
    region: '非洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['冈比亚国防工业', '冈比亚陆军'],
  },
  {
    id: 124,
    name: '几内亚比绍',
    nameEn: 'Guinea-Bissau',
    region: '非洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['几内亚比绍国防工业', '几内亚比绍陆军'],
  },
  {
    id: 125,
    name: '几内亚',
    nameEn: 'Guinea',
    region: '非洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['几内亚国防工业', '几内亚陆军'],
  },
  {
    id: 126,
    name: '塞拉利昂',
    nameEn: 'Sierra Leone',
    region: '非洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['塞拉利昂国防工业', '塞拉利昂陆军'],
  },
  {
    id: 127,
    name: '利比里亚',
    nameEn: 'Liberia',
    region: '非洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['利比里亚国防工业', '利比里亚陆军'],
  },
  {
    id: 128,
    name: '多哥',
    nameEn: 'Togo',
    region: '非洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['多哥国防工业', '多哥陆军'],
  },
  {
    id: 129,
    name: '贝宁',
    nameEn: 'Benin',
    region: '非洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['贝宁国防工业', '贝宁陆军'],
  },
  {
    id: 130,
    name: '南苏丹',
    nameEn: 'South Sudan',
    region: '非洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['南苏丹国防工业', '南苏丹陆军'],
  },
  // 添加更多亚洲国家
  {
    id: 131,
    name: '斯里兰卡',
    nameEn: 'Sri Lanka',
    region: '亚洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['斯里兰卡国防工业', '斯里兰卡陆军'],
  },
  {
    id: 132,
    name: '缅甸',
    nameEn: 'Myanmar',
    region: '亚洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['缅甸国防工业', '缅甸陆军'],
  },
  {
    id: 133,
    name: '柬埔寨',
    nameEn: 'Cambodia',
    region: '亚洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['柬埔寨国防工业', '柬埔寨陆军'],
  },
  {
    id: 134,
    name: '老挝',
    nameEn: 'Laos',
    region: '亚洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['老挝国防工业', '老挝陆军'],
  },
  {
    id: 135,
    name: '蒙古',
    nameEn: 'Mongolia',
    region: '亚洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['蒙古国防工业', '蒙古陆军'],
  },
  {
    id: 136,
    name: '尼泊尔',
    nameEn: 'Nepal',
    region: '亚洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['尼泊尔国防工业', '尼泊尔陆军'],
  },
  {
    id: 137,
    name: '不丹',
    nameEn: 'Bhutan',
    region: '亚洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['不丹国防工业', '不丹陆军'],
  },
  {
    id: 138,
    name: '马尔代夫',
    nameEn: 'Maldives',
    region: '亚洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['马尔代夫国防工业', '马尔代夫陆军'],
  },
  {
    id: 139,
    name: '约旦',
    nameEn: 'Jordan',
    region: '亚洲',
    products: ['M109榴弹炮', 'M60坦克', 'Patriot防空系统'],
    manufacturers: ['约旦国防工业', '约旦陆军'],
  },
  {
    id: 140,
    name: '黎巴嫩',
    nameEn: 'Lebanon',
    region: '亚洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['黎巴嫩国防工业', '黎巴嫩陆军'],
  },
  {
    id: 141,
    name: '叙利亚',
    nameEn: 'Syria',
    region: '亚洲',
    products: ['M101榴弹炮', 'T-72坦克', 'S-300防空系统'],
    manufacturers: ['叙利亚国防工业', '叙利亚陆军'],
  },
  {
    id: 142,
    name: '也门',
    nameEn: 'Yemen',
    region: '亚洲',
    products: ['M101榴弹炮', 'T-72坦克', 'Mistral防空导弹'],
    manufacturers: ['也门国防工业', '也门陆军'],
  },
  {
    id: 143,
    name: '阿曼',
    nameEn: 'Oman',
    region: '亚洲',
    products: ['M109榴弹炮', 'M60坦克', 'Patriot防空系统'],
    manufacturers: ['阿曼国防工业', '阿曼陆军'],
  },
  {
    id: 144,
    name: '卡塔尔',
    nameEn: 'Qatar',
    region: '亚洲',
    products: ['M109榴弹炮', 'M60坦克', 'Patriot防空系统'],
    manufacturers: ['卡塔尔国防工业', '卡塔尔陆军'],
  },
  {
    id: 145,
    name: '科威特',
    nameEn: 'Kuwait',
    region: '亚洲',
    products: ['M109榴弹炮', 'M60坦克', 'Patriot防空系统'],
    manufacturers: ['科威特国防工业', '科威特陆军'],
  },
  {
    id: 146,
    name: '巴林',
    nameEn: 'Bahrain',
    region: '亚洲',
    products: ['M109榴弹炮', 'M60坦克', 'Patriot防空系统'],
    manufacturers: ['巴林国防工业', '巴林陆军'],
  },
  {
    id: 147,
    name: '塞浦路斯',
    nameEn: 'Cyprus',
    region: '亚洲',
    products: ['M101榴弹炮', 'M113装甲车', 'Mistral防空导弹'],
    manufacturers: ['塞浦路斯国防工业', '塞浦路斯陆军'],
  },
  {
    id: 148,
    name: '亚美尼亚',
    nameEn: 'Armenia',
    region: '亚洲',
    products: ['M101榴弹炮', 'T-72坦克', 'S-300防空系统'],
    manufacturers: ['亚美尼亚国防工业', '亚美尼亚陆军'],
  },
  {
    id: 149,
    name: '阿塞拜疆',
    nameEn: 'Azerbaijan',
    region: '亚洲',
    products: ['M101榴弹炮', 'T-72坦克', 'S-300防空系统'],
    manufacturers: ['阿塞拜疆国防工业', '阿塞拜疆陆军'],
  },
  {
    id: 150,
    name: '格鲁吉亚',
    nameEn: 'Georgia',
    region: '亚洲',
    products: ['M101榴弹炮', 'T-72坦克', 'S-300防空系统'],
    manufacturers: ['格鲁吉亚国防工业', '格鲁吉亚陆军'],
  },
  {
    id: 151,
    name: '吉尔吉斯斯坦',
    nameEn: 'Kyrgyzstan',
    region: '亚洲',
    products: ['M101榴弹炮', 'T-72坦克', 'S-300防空系统'],
    manufacturers: ['吉尔吉斯斯坦国防工业', '吉尔吉斯斯坦陆军'],
  },
  {
    id: 152,
    name: '塔吉克斯坦',
    nameEn: 'Tajikistan',
    region: '亚洲',
    products: ['M101榴弹炮', 'T-72坦克', 'S-300防空系统'],
    manufacturers: ['塔吉克斯坦国防工业', '塔吉克斯坦陆军'],
  },
  {
    id: 153,
    name: '土库曼斯坦',
    nameEn: 'Turkmenistan',
    region: '亚洲',
    products: ['M101榴弹炮', 'T-72坦克', 'S-300防空系统'],
    manufacturers: ['土库曼斯坦国防工业', '土库曼斯坦陆军'],
  },
  {
    id: 154,
    name: '乌兹别克斯坦',
    nameEn: 'Uzbekistan',
    region: '亚洲',
    products: ['M101榴弹炮', 'T-72坦克', 'S-300防空系统'],
    manufacturers: ['乌兹别克斯坦国防工业', '乌兹别克斯坦陆军'],
  },
  {
    id: 155,
    name: '哈萨克斯坦',
    nameEn: 'Kazakhstan',
    region: '亚洲',
    products: ['M101榴弹炮', 'T-72坦克', 'S-300防空系统'],
    manufacturers: ['哈萨克斯坦国防工业', '哈萨克斯坦陆军'],
  },
];

// 搜索字段配置
export const countrySearchFields = ['name', 'nameEn', 'region', 'products', 'manufacturers'];

// 搜索建议
export const countrySuggestions = [
  '中国',
  '美国',
  '俄罗斯',
  '德国',
  '法国',
  '英国',
  '以色列',
  '韩国',
  '阿联酋',
  '日本',
  '印度',
  '新加坡',
  '泰国',
  '印度尼西亚',
  '马来西亚',
  '越南',
  '菲律宾',
  '孟加拉国',
  '巴基斯坦',
  '土耳其',
  '沙特阿拉伯',
  '伊朗',
  '伊拉克',
  '荷兰',
  '瑞士',
  '瑞典',
  '挪威',
  '丹麦',
  '芬兰',
  '波兰',
  '捷克',
  '奥地利',
  '比利时',
  '爱尔兰',
  '葡萄牙',
  '希腊',
  '匈牙利',
  '加拿大',
  '墨西哥',
  '巴西',
  '阿根廷',
  '智利',
  '哥伦比亚',
  '秘鲁',
  '委内瑞拉',
  '乌拉圭',
  '厄瓜多尔',
  '玻利维亚',
  '巴拉圭',
  '南非',
  '埃及',
  '尼日利亚',
  '埃塞俄比亚',
  '肯尼亚',
  '坦桑尼亚',
  '乌干达',
  '加纳',
  '科特迪瓦',
  '塞内加尔',
  '马里',
  '澳大利亚',
  '新西兰',
  '斐济',
  '巴布亚新几内亚',
  '亚洲',
  '欧洲',
  '北美洲',
  '南美洲',
  '非洲',
  '大洋洲',
  '导弹',
  '榴弹炮',
  '坦克',
  '防空系统',
  '装甲车',
  '火箭炮',
  // 阿联酋相关
  'EDGE集团',
  'AGRAB迫击炮',
  'NEMO迫炮塔',
  '卫星制导迫弹',
  '霍尔木兹海峡',
  '也门冲突',
  '胡塞武装',
  '迫击炮',
  '加农炮',
  '自行榴弹炮',
  '车载榴弹炮',
  '轻型榴弹炮',
];
